# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

# vars:

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: 本番環境のデプロイ
    preconditions:
      - sh: '[[ "$(hostname)" =~ ^ftt ]]'
        msg: "本番環境のみ有効です"
    dir: webapp
    cmds:
      - task: checkout
      - bash -x restart_container.sh

  local:
    desc: ローカル環境のデプロイ
    preconditions:
      - sh: '[[ ! "$(hostname)" =~ ^ftt ]]'
        msg: "ローカル環境のみ有効です"
    dir: webapp
    cmds:
      - bash -x restart_container.sh

  test:
    desc: テストを実行
    dir: webapp/e2e
    cmds:
      - bash -x run_e2e_test.sh

  bench:
    desc: ベンチマークを実行
    preconditions:
      - sh: '[[ "$(hostname)" =~ ^ftt ]]'
        msg: "本番環境のみ有効です"
    dir: /home/azureuser/shark-42Tokyo-Tuning-2509/
    cmds:
      - bash -x run.sh

  restore:
    desc: データベースのリストア & マイグレーション
    cmds:
      - bash -x restore_and_migration.sh

  ####################
  #     Utility      #
  ####################
  checkout:
    desc: リモートブランチに強制的にチェックアウト
    vars:
      BRANCH:
        sh: if [[ -z "{{.CLI_ARGS}}" ]]; then git branch --show-current; else echo "{{.CLI_ARGS}}"; fi
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  ####################
  #     Internal     #
  ####################
