services:
  otel-collector-agent:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.129.5}
    container_name: signoz-otel-collector-agent
    user: "0:0"
    command:
      - --config=/etc/otel-collector/config/otel-collector-config.agent.yaml
      - --copy-path=/var/tmp/collector-config.yaml
    volumes:
      - ./config:/etc/otel-collector/config:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /:/hostfs:ro
      - nginx_logs:/var/log/nginx:ro
    environment:
      OTEL_RESOURCE_ATTRIBUTES: "host.name=vm"
      LOW_CARDINAL_EXCEPTION_GROUPING: false
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ROOT: /hostfs
      NGINX_ACCESS_LOG_FILE: /var/log/nginx/_access.log
      NGINX_ERROR_LOG_FILE: /var/log/nginx/_error.log
      EXTERNAL_OTLP_ENDPOINT: "54.249.224.29:4317"
    ports:
      # - "1777:1777"     # pprof extension
      - "14317:4317" # OTLP gRPC receiver
      - "14318:4318" # OTLP HTTP receiver
    networks:
      - webapp-network

volumes:
  nginx_logs:
    external: true

networks:
  webapp-network:
    external: true
